### PR TITLE
Pep8 stylistic

### PR DESCRIPTION
**Pull request by Tomaszsachanowski**
Branch solves stylistic problems. Adapted to pep8

### CODE REVIEW

**Comment by tobiaszjarosiewicz** [comment]
Is line breaking here on purpose?
https://github.com/European-XFEL/CrystFEL-Jupyter-utilities/blob/fb3a096e22f33276d8ecaa6ae0da863b54be2fc0/CrystFEL_Jupyter_utilities/crystlib.py#L53-L54

I suggest:
```
    dict_data = {key: crystal_search(cryst, key) for key in histogram_order}
```

**Comment by tobiaszjarosiewicz** [comment]
Blank lines:
https://github.com/European-XFEL/CrystFEL-Jupyter-utilities/blob/fb3a096e22f33276d8ecaa6ae0da863b54be2fc0/CrystFEL_Jupyter_utilities/GUI_tools.py#L325
https://github.com/European-XFEL/CrystFEL-Jupyter-utilities/blob/fb3a096e22f33276d8ecaa6ae0da863b54be2fc0/CrystFEL_Jupyter_utilities/GUI_tools.py#L334
https://github.com/European-XFEL/CrystFEL-Jupyter-utilities/blob/fb3a096e22f33276d8ecaa6ae0da863b54be2fc0/CrystFEL_Jupyter_utilities/GUI_tools.py#L413

**Comment by tobiaszjarosiewicz** [comment]
Blank lines in following section:
https://github.com/European-XFEL/CrystFEL-Jupyter-utilities/blob/fb3a096e22f33276d8ecaa6ae0da863b54be2fc0/CrystFEL_Jupyter_utilities/hdfsee.py#L313-L352

In CrystFEL_Jupyter_utilities/hdfsee.py lines 373, 386, 391, 398.

**Comment by Tomaszsachanowski** [comment]
https://github.com/European-XFEL/CrystFEL-Jupyter-utilities/pull/10#issuecomment-586987447. 
Done in:  d091d2448bd87a464f03fb70a195b71ea39c16f9.

**Comment by Tomaszsachanowski** [comment]
https://github.com/European-XFEL/CrystFEL-Jupyter-utilities/pull/10#issuecomment-587003788
https://github.com/European-XFEL/CrystFEL-Jupyter-utilities/pull/10#issuecomment-587012839
Done in: f654931753eb55cc76106c6d0863b4fbf2d3592b.

**Comment by tobiaszjarosiewicz** [comment]
LGTM

**Pull request merged**
